// external imports
import dynamic from 'next/dynamic';
import { ThemeProvider } from '@material-ui/styles';
// internal imports
import generateMuiTheme from '../src/mui/theme';
import Head from 'next/head';
const MeetingAppContainer = dynamic(
  () => import('../src/containers/MeetingAppContainer'),
  {
    ssr: false,
  }
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Conference Room</title>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
        />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ThemeProvider theme={generateMuiTheme()}>
        <MeetingAppContainer />
      </ThemeProvider>
    </>
  );
}
